spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/EmployeePortal
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwtSecret=mySecretKeyForJWTTokenGenerationAndValidation2024@#$%^&*()_+-=[]{}|;:',.<>?/
app.jwtExpirationMs=86400000

logging.level.root=INFO
logging.level.com.example.attendance=DEBUG
logging.level.org.springframework.security=DEBUG

